os:
  - osx
  - linux

env:
  - JS_FRAMEWORK=angular-v1.6.3-keyed
  - JS_FRAMEWORK=angular-v4.1.2-keyed
  - JS_FRAMEWORK=angular-v4.1.2-no-zone-keyed
  - JS_FRAMEWORK=angular-v4.1.2-non-keyed
  - JS_FRAMEWORK=aurelia-v1.1.2-non-keyed
  - JS_FRAMEWORK=binding.scala-v10.0.1-keyed
  - JS_FRAMEWORK=bobril-v7.1.2-keyed
  - JS_FRAMEWORK=choo-v5.4.0-non-keyed
  - JS_FRAMEWORK=cyclejs-dom-v17.1.0-non-keyed
  - JS_FRAMEWORK=datum-v0.8.0-non-keyed
  - JS_FRAMEWORK=dio-v7.0.1-keyed
  - JS_FRAMEWORK=dio-v7.0.1-non-keyed
  - JS_FRAMEWORK=domvm-v3.0.1-keyed
  - JS_FRAMEWORK=domvm-v3.0.1-non-keyed
  - JS_FRAMEWORK=elm-v0.18.0-keyed
  - JS_FRAMEWORK=ember-v2.13.0-keyed
  - JS_FRAMEWORK=glimmer-v0.3.10-keyed
  - JS_FRAMEWORK=hyperapp-v0.9.1-non-keyed
  - JS_FRAMEWORK=inferno-v3.1.2-keyed
  - JS_FRAMEWORK=inferno-v3.1.2-non-keyed
  - JS_FRAMEWORK=ivi-v0.8.0-keyed
  - JS_FRAMEWORK=knockout-v3.4.1-keyed
  - JS_FRAMEWORK=marionette-v3.3.1-keyed
  - JS_FRAMEWORK=marko-v4.3.0-keyed
  - JS_FRAMEWORK=mithril-v1.1.1-keyed
  - JS_FRAMEWORK=nx-v1.0.0-beta.2.0.1-keyed
  - JS_FRAMEWORK=nx-v1.0.0-beta.2.0.1-non-keyed
  - JS_FRAMEWORK=pico-dom-v1.0.0-keyed
  - JS_FRAMEWORK=plastiq-v1.33.0-keyed
  - JS_FRAMEWORK=polymer-v2.0.0-non-keyed
  - JS_FRAMEWORK=preact-v7.1.0-keyed
  - JS_FRAMEWORK=ractive-v0.8.12-keyed
  - JS_FRAMEWORK=ractive-v0.8.12-non-keyed
  - JS_FRAMEWORK=ractive-edge-keyed
  - JS_FRAMEWORK=ractive-edge-non-keyed
  - JS_FRAMEWORK=react-lite-v0.15.30-keyed
  - JS_FRAMEWORK=react-v15.5.4-easy-state-v1.0.3-keyed
  - JS_FRAMEWORK=react-v15.5.4-keyed
  - JS_FRAMEWORK=react-v15.5.4-mobX-v3.1.9-keyed
  - JS_FRAMEWORK=react-v15.5.4-non-keyed
  - JS_FRAMEWORK=react-v15.5.4-redux-v3.6.0-keyed
  - JS_FRAMEWORK=react-v16.alpha.13-keyed
  - JS_FRAMEWORK=redom-v3.0.2-keyed
  - JS_FRAMEWORK=redom-v3.0.2-non-keyed
  - JS_FRAMEWORK=riot-v3.5.0-non-keyed
  - JS_FRAMEWORK=rx-domh-v0.0.2-rxjs-v5.3.0-keyed
  - JS_FRAMEWORK=simulacra-v2.1.1-non-keyed
  - JS_FRAMEWORK=slim-js-v3.3.0-non-keyed
  - JS_FRAMEWORK=stem-v0.2.70-non-keyed
  - JS_FRAMEWORK=surplus-v0.4.0-keyed
  - JS_FRAMEWORK=surplus-v0.4.0-non-keyed
  - JS_FRAMEWORK=svelte-v1.20.2-keyed
  - JS_FRAMEWORK=svelte-v1.20.2-non-keyed
  - JS_FRAMEWORK=tsers-v1.0.0-non-keyed
  - JS_FRAMEWORK=vanillajs-keyed
  - JS_FRAMEWORK=vanillajs-non-keyed
  - JS_FRAMEWORK=vidom-v0.9.8-keyed
  - JS_FRAMEWORK=vue-v2.3.3-keyed
  - JS_FRAMEWORK=vue-v2.3.3-non-keyed

language : node_js
node_js  : 7

addons:
  chrome: beta

install: true

# https://docs.travis-ci.com/user/gui-and-headless-browsers/#Starting-a-Web-Server
# https://github.com/travis-ci/travis-ci/issues/7313#issuecomment-279914149
before_script:
  - export DISPLAY=:99.0
  - if [ "${TRAVIS_OS_NAME}" = "osx"   ]; then (sudo Xvfb :99 -ac -screen 0 1024x768x8; echo ok)& fi
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then (sh -e /etc/init.d/xvfb start) fi
  - sleep 3                             # give xvfb some time to start
  
script:
  - npm install
  - npm start &                         # start a Web server
  - sleep 3                             # give Web server some time to bind to sockets, etc
  - cd $JS_FRAMEWORK
  - yarn
  - npm run build-prod
  - cd ../webdriver-ts
  - yarn
  - npm run build-prod
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then  (npm run selenium -- --framework $JS_FRAMEWORK --count 1 --benchmark 01_ 02_ 03_ 04_ 05_ 06_) fi
  
git:
  depth: 5
