version: 2
jobs:
  build:
    machine:
      java:
        version: oraclejdk8

    steps:
      - checkout

      - run: |
          curl -L -o google-chrome.deb https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome.deb
          sudo sed -i 's|HERE/chrome\"|HERE/chrome\" --disable-setuid-sandbox|g' /opt/google/chrome/google-chrome
          rm google-chrome.deb

      - run: |
          source $NVM_DIR/nvm.sh
          nvm install v8.9.1
          nvm use v8.9.1
          nvm alias default v8.9.1
          node -v
#          nvm uninstall default
#          curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
#          sudo apt-get install -y nodejs

      - run: npm install
      - run:
          name: Start http-server
          command: npm start
          background: true
      - run: npm run build
      - run: npm run check
